name: Chrome Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 14.x
        chrome-version:
          - stable
          - beta
          - dev

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: ${{ matrix.chrome-version }}
      - run: npm ci
      - run: which chrome
      - run: chrome --version
      - run: CHROME_BIN=$(which chrome) npm test
